In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("online_retail_II.csv")

In [3]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [4]:
df.shape

(1067371, 8)

In [5]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [7]:
df["InvoiceDate"].head(5)

0    2009-12-01 07:45:00
1    2009-12-01 07:45:00
2    2009-12-01 07:45:00
3    2009-12-01 07:45:00
4    2009-12-01 07:45:00
Name: InvoiceDate, dtype: object

In [8]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], errors="coerce")

In [9]:
df["InvoiceDate"].dtype

dtype('<M8[ns]')

In [10]:
df["InvoiceDate"].isna().sum()

0

In [11]:
df = df[df["InvoiceDate"].notna()]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [14]:
df = df[~df["Invoice"].astype(str).str.startswith("C")]

In [15]:
df["Invoice"].head()

0    489434
1    489434
2    489434
3    489434
4    489434
Name: Invoice, dtype: object

In [17]:
df = df[(df["Quantity"] > 0) & (df["Price"] > 0)]

In [18]:
df[["Quantity", "Price"]].describe()

           Quantity         Price
count  1.041670e+06  1.041670e+06
mean   1.096346e+01  4.076683e+00
std    1.265150e+02  5.144773e+01
min    1.000000e+00  1.000000e-03
25%    1.000000e+00  1.250000e+00
50%    3.000000e+00  2.100000e+00
75%    1.000000e+01  4.130000e+00
max    8.099500e+04  2.511109e+04

In [19]:
df["total_amount"] = df["Quantity"] * df["Price"]

C:\Users\bunty\AppData\Local\Temp\ipykernel_33004\1961403836.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["total_amount"] = df["Quantity"] * df["Price"]

In [21]:
df[["Quantity", "Price", "total_amount"]].head()

   Quantity  Price  total_amount
0        12   6.95          83.4
1        12   6.75          81.0
2        12   6.75          81.0
3        48   2.10         100.8
4        24   1.25          30.0

In [23]:
clean_df = df[
    [
        "Customer ID",
        "Invoice",
        "InvoiceDate",
        "Quantity",
        "Price",
        "total_amount"
    ]
]

In [24]:
clean_df.head()

   Customer ID Invoice         InvoiceDate  Quantity  Price  total_amount
0      13085.0  489434 2009-12-01 07:45:00        12   6.95          83.4
1      13085.0  489434 2009-12-01 07:45:00        12   6.75          81.0
2      13085.0  489434 2009-12-01 07:45:00        12   6.75          81.0
3      13085.0  489434 2009-12-01 07:45:00        48   2.10         100.8
4      13085.0  489434 2009-12-01 07:45:00        24   1.25          30.0

In [26]:
clean_df.to_csv(
    "clean_transactions.csv",
    index=False
)